### ISSUE TITLE
E: Unable to locate package alltomp3

### ISSUE THREAD

**Issue by marcellendi** [AllToMP3/alltomp3-app#78]
**Curl works ok (i think):**
curl -s https://packagecloud.io/install/repositories/AllToMP3/alltomp3/script.deb.sh | sudo bash
Detected operating system as Ubuntu/bionic.
Checking for curl...
Detected curl...
Checking for gpg...
Detected gpg...
Running apt-get update... done.
Installing apt-transport-https... done.
Installing /etc/apt/sources.list.d/AllToMP3_alltomp3.list...done.
Importing packagecloud gpg key... done.
Running apt-get update... done.

The repository is setup! You can now install packages."

**But install fails**
sudo apt-get install alltomp3
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package alltomp3

**Comment by harshitdiit** [comment]
This is because a release file has not been added for 18.04
@NTag Please add a release file.
`E: The repository 'https://packagecloud.io/AllToMP3/alltomp3/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.`

**Comment by NTag** [comment]
Can you try again? I just pushed the latest version 0.3.6 to Ubuntu Bionic.

**Comment by harshitdiit** [comment]
Working now, cheers @NTag 
Great work man!

**Comment by marcellendi** [comment]
Great it works! Thank you for the quick response!
